services:

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    restart: always
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

  spark:
    build: ./spark
    container_name: spark
    restart: always
    depends_on:
      - kafka
    ports:
      - "4040:4040"
    volumes:
      - ./app:/app
      - ./data:/data

  airflow-postgres:
    image: postgres:13
    container_name: airflow-postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"

  airflow-webserver:
    image: apache/airflow:2.7.0
    container_name: airflow-webserver
    user: root
    depends_on:
      - airflow-postgres
      - airflow-init
    environment:
      AIRFLOW__WEBSERVER__SECRET_KEY: mysecretkey123
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-postgres/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      DOCKER_HOST: unix:///var/run/docker.sock
      DOCKER_API_VERSION: "1.44"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./app:/app
      - ./data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080"
    command: airflow webserver
    restart: always

  airflow-scheduler:
    image: apache/airflow:2.7.0
    container_name: airflow-scheduler
    user: root
    depends_on:
      - airflow-webserver
      - airflow-init
    environment:
      AIRFLOW__WEBSERVER__SECRET_KEY: mysecretkey123
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-postgres/airflow
      DOCKER_API_VERSION: "1.44"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./app:/app
      - ./data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    command: airflow scheduler
    restart: always

  airflow-init:
    image: apache/airflow:2.7.0
    depends_on:
      airflow-postgres:
        condition: service_started
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-postgres/airflow
    command: >
      bash -c "airflow db init && airflow users create
      --username airflow
      --password airflow
      --firstname admin
      --lastname user
      --role Admin
      --email admin@email.com"